site_name: Parallel Programming

theme:
  name: lumen

markdown_extensions:
  - markdown.extensions.admonition
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

plugins:
  - search
  - autorefs
  - mkdocstrings
  - mkdocs-video

nav:
  - index.md
  - glossary.md
  - links.md
  - overview.md
  - course-text.md
  - exercices.md
  - evaluation.md
  - vsc-infrastructure.md
