site_name: Parallel programmeren

theme:
  name: "material"

nav:
  - index.md
  - over-de-auteur.md
  - aanwijzigingen.md
  - inleiding.md
  - hoofdstuk-1.md
  - evaluation.md

extra_css:
    - css/extra.css

markdown_extensions:
     - markdown.extensions.admonition