site_name: Parallel programmeren

theme:
  name: "material"

nav:
  - index.md
  - over-de-auteur.md
  - guide-lines.md
  - introduction.md
  - chapter-1.md
  - evaluation.md
  - assignment.md

extra_css:
    - css/extra.css

markdown_extensions:
     - markdown.extensions.admonition
     - mkdocs-video