site_name: Parallel programmeren

theme:
  name: "material"

nav:
  - index.md
  - over-de-auteur.md
  - glossary.md
  - links.md
  - overview.md
  - chapter-1.md
  - chapter-2.md
  - chapter-3.md
  - chapter-4.md
  - evaluation.md
  - assignment.md
  - guide-lines.md

markdown_extensions:
    - markdown.extensions.admonition

plugins:
  - search
  - autorefs
  - mkdocstrings
  - mkdocs-video